name: Yuval Marcus
description: "Simply, a blog."
meta_description: "A blog by Yuval Marcus."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://yuvalmarcus.io'
google_analytics: 'UA-XXXXXXXX-X'

gems: [nokogiri]

# Details for the RSS feed generator
url:            'yuvalmarcus.io'
author:         'Yuval Marcus'